# Generated by Django 5.2.6 on 2025-09-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.CharField(blank=True, choices=[('world', 'World News'), ('local', 'Local News')], default='world', max_length=10),
        ),
    ]
