# Generated by Django 5.2.6 on 2025-09-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0005_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='source',
            field=models.CharField(choices=[('AI', 'AI'), ('Summarizer', 'Summarizer')], default='AI', max_length=20),
        ),
    ]
